[package]
name = "dronoid-client"
version = "0.1.0"
authors = ["Primo <primo.contact@mail.fr>"]
edition = '2024'

[dependencies]
bevy_color = "0.19.1"
bevy_state = "0.19.1"

[dependencies.dronoid]
version = "0.1.0"
path = "../library"

[dependencies.dronoid-common]
version = "0.1.0"
path = "../common"

[dependencies.addr]
version = "0.15.6"
default-features = false

[dependencies.anyhow]
version = "1.0.104"
default-features = false

[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
version = "0.19.1"
features = ["2d", "bevy_ui_widgets", "bevy_color"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.19.1"
features = ["2d", "bevy_ui_widgets", "bevy_color", "dynamic_linking"]

[dependencies.bevy_app]
version = "0.19.1"
default-features = false

[dependencies.bevy_ecs]
version = "0.19.1"
default-features = false
features = ["debug"]

[dependencies.bson]
version = "3.1.0"
default-features = false

[dependencies.crossbeam-channel]
version = "0.5.17"
default-features = false

[target.'cfg(target_arch = "wasm32")'.dependencies.getrandom]
version = "0.4.3"
default-features = false
features = ["wasm_js"]

[target.'cfg(target_arch = "wasm32")'.dependencies.rand]
version = "0.10.2"
default-features = false
features = ["thread_rng"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.rand]
version = "0.10.2"
default-features = false

[dependencies.validator]
version = "0.21.0"
default-features = false

[dependencies.wasm-bindgen]
version = "0.2.128"
default-features = false

[dependencies.web-sys]
version = "0.3.105"
default-features = false
features = ["Window", "Location", "BinaryType"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.display-info]
version = "0.5.9"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tungstenite]
version = "0.30.0"
default-features = false
features = ["rustls-tls-webpki-roots", "handshake"]

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.105"
default-features = false
features = ["WebSocket", "MessageEvent", "ErrorEvent", "CloseEvent"]
