[package]
name = "dronoid"
version = "0.1.0"
authors = ["Primo <primo.contact@mail.fr>"]
edition = '2024'

[lib]
test = false
doctest = false

[[bin]]
name = "server"
test = false
doctest = false

[[bin]]
name = "client"
test = false
doctest = false

[dependencies]
addr = "0.15.6"
anyhow = "1.0.104"
bevy = { version = "0.19.1", features = ["dynamic_linking"] }
bevy_app = "0.19.1"
bevy_ecs = { version = "0.19.1", features = ["debug"] }
bevy_framepace = "0.22.0"
bson = { version = "3.1.0", features = ["serde"] }
clap = { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
crossbeam-channel = "0.5.16"
display-info = "0.5.9"
futures = "0.3.34"
noise = "0.9.0"
rand = "0.10.2"
rapier2d = "0.35.3"
serde = "1.0.229"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
    "time",
    "macros",
    "rt",
    "sync",
    "test-util",
    "rt-multi-thread",
    "signal",
] }
tokio-tungstenite = "0.30.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
validator = "0.21.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
